config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check
  # get '/', to: 'home#index'
  root to: 'home#index'
  # get '/ola', to: 'home#ola' # visitante => (/ola) => home_controller => ola(action/metodo 'def') => resposta (view)

  # Defines the root path route ("/")
  # root "posts#index"

  # get 'receitas/:id', to: 'recipes#show', as: 'recipe'
  resources :recipes, only: [:show, :new, :create, :edit, :update] do
    patch :publish, on: :member
    patch :draft, on: :member
  end
  resources :recipe_types, only: [:new, :create]
  resources :cuisines, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  enum status: {draft: 0, published: 2}
  belongs_to :recipe_type
  belongs_to :cuisine
end

app/models/recipe_type.rb
class RecipeType < ApplicationRecord
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  def new
    @cuisine = Cuisine.new
  end

  def create
    @cuisine = Cuisine.new(name: params[:cuisine][:name])

    if @cuisine.save
      flash[:notice] = "Tipo de Culinária criado com sucesso"
      return redirect_to(new_cuisine_path)
    end

    render :new
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # @recipe = Recipe.new(name: 'Pudim', recipe_type: 'Sobremesa')
    # r1 = Recipe.new(name: 'Pudim', recipe_type: 'Sobremesa')
    # r2 = Recipe.new(name: 'Bolo de cenoura', recipe_type: 'Sobremesa')

    # recipes = [r1, r2]

    # render plain: 'Página principal'
    # render template: 'index' # view/home/index.html.erb

    # @recipes = Recipe.all #(chama o model"Recipe" com o método 'all')
    @recipes = Recipe.published #(chama o model "Recipe" com o método status = published)
  end
  
  # def ola
  #   # render plain: 'Ola'
  #   render plain: 'Você está na página (/ola)'
  # end
end

app/controllers/recipe_types_controller.rb
class RecipeTypesController < ApplicationController

  def new
    @recipe_type = RecipeType.new
  end

  def create
    @recipe_type = RecipeType.new(name: params[:recipe_type][:name])

    if @recipe_type.save
      flash[:notice] = "Tipo de Receita criado com sucesso"
      # flash.notice = "Tipo de Receita criado com sucesso" # ou nessa notação
      return redirect_to(new_recipe_type_path)
    end

    render :new

  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(name: params[:recipe][:name], 
      recipe_type_id: params[:recipe][:recipe_type_id],
      # cuisine: params[:recipe][:cuisine],
      cuisine_id: params[:recipe][:cuisine_id],
      ingredients: params[:recipe][:ingredients],
      cook_method: params[:recipe][:cook_method],
      cook_time: params[:recipe][:cook_time])

    if @recipe.save
      return redirect_to recipe_path(@recipe.id)
    end

    render :new
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(name: params[:recipe][:name], 
    recipe_type_id: params[:recipe][:recipe_type_id],
    cuisine_id: params[:recipe][:cuisine_id],
    ingredients: params[:recipe][:ingredients],
    cook_method: params[:recipe][:cook_method],
    cook_time: params[:recipe][:cook_time])

      return redirect_to recipe_path(@recipe.id)
    end

    render :edit
  end

  def publish
    recipe = Recipe.find(params[:id])
    recipe.published!
    return redirect_to recipe_path(recipe.id)
  end
  def draft
    recipe = Recipe.find(params[:id])
    recipe.draft!
    return redirect_to recipe_path(recipe.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cuisines/new.html.erb
<h1>Registro de tipos de cozinhas</h1>
<% if flash[:notice] %>
  <div style="margin: 10px 0px">
  <%= flash[:notice]  %>
  </div>
<% end %>



<%= form_with model: @cuisine do | f | %>

<div>
  <%= f.label :name, 'Nome' %>
  <%= f.text_field :name %>
</div>

<div style='margin: 10px 5px'>
  <%= f.submit 'Salvar'%>
</div>


<%end%>

app/views/home/index.html.erb
<h1>Livro de receitas</h1>

<% @recipes.each do |recipe|%>
<!-- <strong>Nome: </strong> <%=recipe.name%> <br /> -->

<%# Método usando tag '<a></a>' %>
<!-- <a href='/receitas/<%= recipe.id%>'> <%=recipe.name%> </a><br /> -->

<%# Método usando link_to %>
<%= link_to recipe.name, recipe_path(recipe.id) %>
<!-- <%= link_to recipe.name, recipe %>  # forma resumida-->
<br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <ul>
        <li>
          <%= link_to 'Home', root_path  %>
        </li>
        <li>
          <%= link_to 'Cadastrar nova receita', new_recipe_path  %>
        </li>
        <li>
          <%= link_to 'Cadastrar novo tipo de receita', new_recipe_type_path  %>
        </li>

        <li>
          <%= link_to 'Cadastrar novo tipo de culinária', new_cuisine_path  %>
        </li>

      </ul>


    </nav>



    <%= yield %>
  </body>

</html>

app/views/recipe_types/new.html.erb
<h1>Registro de tipo de receita</h1>
<% if flash[:notice] %>
<div style="margin: 10px 0px">
  <%= flash[:notice] %>
</div>

<%end%>


<%= form_with model: @recipe_type do |f| %>
<div>
  <%= f.label :name, 'Nome' %>
  <%= f.text_field :name %>
</div>

<div>
   <%= f.submit 'Salvar' %>
</div>


<%end%>

app/views/recipes/_form.html.erb
<%= form_with model: recipe do | f |  %>
<%= f.label 'Nome'%>
<%= f.text_field :name %>

<%= f.label 'Tipo de receita'%>
<%= f.collection_select :recipe_type_id, RecipeType.all, :id, :name  %>

<%= f.label 'Culinária'%>
<%= f.collection_select :cuisine_id, Cuisine.all, :id, :name %>

<%= f.label 'Ingredientes'%>
<%= f.text_area :ingredients %>

<%= f.label 'Modo de preparo'%>
<%= f.text_field :cook_method %>

<%= f.label 'Tempo de preparo:'%>
<%= f.number_field :cook_time %>

<%= f.submit "Salvar"%>

<%end%>

app/views/recipes/edit.html.erb
<%= render partial: 'form', locals: {recipe: @recipe}  %>

app/views/recipes/new.html.erb
<%= form_with model: @recipe do | f |  %>
<%= f.label 'Nome'%>
<%= f.text_field :name %>

<%= f.label 'Tipo de receita'%>
<!-- <%= f.text_field :recipe_type %> -->
<%= f.collection_select :recipe_type_id, RecipeType.all, :id, :name  %>

<%= f.label 'Culinária'%>
<%= f.text_field :cuisine %>

<%= f.label 'Ingredientes'%>
<%= f.text_area :ingredients %>

<%= f.label 'Modo de preparo'%>
<%= f.text_field :cook_method %>

<%= f.label 'Tempo de preparo:'%>
<%= f.number_field :cook_time %>

<%= f.submit "Salvar"%>


<%end%>

app/views/recipes/show.html.erb
<h1>Informações sobre a receita: <%= @recipe.name%></h1>
<%= link_to "Editar", edit_recipe_path %>

<dl>
<dt>
<strong>Nome: </strong> <%=@recipe.name%>
</dt>

<dd>
  <strong>Tipo da Receita: </strong><%=@recipe.recipe_type.name%>
  </dd>
<dd>
  <strong>Culinária: </strong><%=@recipe.cuisine.name if @recipe.cuisine %>
  </dd>
<dd>
  <strong>Ingredientes: </strong><%=@recipe.ingredients%>
  </dd>
<dd>
  <strong>Modo de preparo: </strong><%=@recipe.cook_method%>
  </dd>
<dd>
  <strong>Tempo de preparo: </strong><%=@recipe.cook_time%>
  </dd>
<dd>
  <strong>Status: </strong><%=@recipe.status%>
  </dd>
</dl>

<%= button_to 'Publicar', publish_recipe_path, {method: 'patch'} %>
<%= button_to 'Rascunho', draft_recipe_path, {method: 'patch'} %>